<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'code',
        'serail_number',
        'name',
        'item_id',
        'size',
        'source',
        'place_found',
        'company_created',
        'catogry_color',
        'country_created',
        'type',
        'modal',
        'production_date',
        'production_end_date',
        'unit_one_name',
        'unit_one_barcode',
        'unit_one_default',
        'unit_one_max_limit',
        'unit_one_min_limit',
        'unit_one_request_limit',
        'unit_tow_name',
        'unit_tow_barcode',
        'unit_tow_factor_converter',
        'unit_tow_default',
        'unit_tow_max_limit',
        'unit_tow_min_limit',
        'unit_tow_request_limit',
        'unit_three_name',
        'unit_three_barcode',
        'unit_three_factor_converter',
        'unit_three_default',
        'unit_three_max_limit',
        'unit_three_min_limit',
        'unit_three_request_limit',
        'unit_one_price_jumla',
        'unit_one_price_half_jumla',
        'unit_one_price_disterbuted',
        'unit_one_price_export',
        'unit_one_price_peices',
        'unit_one_price_consumer',
        'unit_one_price_default',
        'unit_tow_price_jumla',
        'unit_tow_price_half_jumla',
        'unit_tow_price_disterbuted',
        'unit_tow_price_export',
        'unit_tow_price_peices',
        'unit_tow_price_consumer',
        'unit_tow_price_default',
        'unit_three_price_jumla',
        'unit_three_price_half_jumla',
        'unit_three_price_disterbuted',
        'unit_three_price_export',
        'unit_three_price_peices',
        'unit_three_price_consumer',
        'unit_three_price_default',
    ];
}
